version: '3'

services:
  landing:
    container_name: landing
    image: landing:latest
    build:
      context: .
      dockerfile: ./apps/landing/Dockerfile
    restart: always
    ports:
      - 9017:3000
    networks:
      - network1

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  network1:
    external: true
